ok

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -6,9 +6,9 @@ on:
       - main  # Trigger the pipeline on push to the main branch
 
 jobs:
-  # Backend Workflow
-  backend:
+  build-backend:
     runs-on: ubuntu-latest
+
     steps:
       # Step 1: Checkout the repository
       - name: Checkout code
@@ -20,7 +20,7 @@ jobs:
 
       # Step 3: Log in to Docker Hub
       - name: Log in to Docker Hub
-        uses: docker/login-action@v3
+        uses: docker/login-action@v3 
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
@@ -28,16 +28,15 @@ jobs:
       # Step 4: Build Backend Docker images
       - name: Build Backend Docker images
         run: |
+          set -e  # Exit on error
+          echo "Building API Gateway Image..."
           docker build -t ${{ secrets.DOCKER_USERNAME }}/crud-micro:api-gateway -f ./Back_End/API_Gateway/Dockerfile ./Back_End/API_Gateway
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/crud-micro:user-service -f ./Back_End/User-Management_Service/Dockerfile ./Back_End/User-Management_Service
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/crud-micro:notification -f ./Back_End/User-Notification_Service/Dockerfile ./Back_End/User-Notification_Service
 
-      # Step 5: Push Backend Docker images
-      - name: Push Backend Docker images
-        run: |
-          docker push ${{ secrets.DOCKER_USERNAME }}/crud-micro:api-gateway
-          docker push ${{ secrets.DOCKER_USERNAME }}/crud-micro:user-service
-          docker push ${{ secrets.DOCKER_USERNAME }}/crud-micro:notification
+          echo "Building User Service Image..."
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/crud-micro:user-service -f ./Back_End/User-Management_Service/Dockerfile ./Back_End/User-Management_Service
+
+          echo "Building Notification Service Image..."
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/crud-micro:notification -f ./Back_End/User-Notification_Service/Dockerfile ./Back_End/User-Notification_Service
 
   # # Frontend Workflow
   # frontend:
